version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblio
      MYSQL_USER: root
      MYSQL_PASSWORD: toutoutou
    volumes:
      - dbdata:/var/lib/mysql
      # Tu peux ajouter un init.sql si tu veux pré-créer les tables :
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dbdata: